[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = default.csv

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=1
    -D PIN_DISPLAY_CS=10
    -D PIN_DISPLAY_DC=11
    -D PIN_DISPLAY_RST=7
    -D PIN_DISPLAY_SCLK=9
    -D PIN_DISPLAY_MOSI=8
    -D PIN_DISPLAY_BL=14
    -D PIN_DISPLAY_PWR=13
    -D TFT_WIDTH=320
    -D TFT_HEIGHT=240

lib_deps = 
    bodmer/TJpg_Decoder @ ^1.0.8

upload_speed = 921600
monitor_speed = 115200
